spring:
  application:
    name: stock

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.129:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

  reids:
    host: 192.168.182.129
    port: 6379
    # #redis请求超时时间，超过此值redis自动断开连接
    timeout: 10000ms
    jedis:
      pool:
        # jedis最大连接数，超过此值则提示获取不到连接异常
        max-active: 32
        # jedis最大等待时间，超过此值会提示连接超时异常
        max-wait: 10000ms
        # jedis最大等待连接数
        max-idle: 32
        # jedis最小等待连接数
        min-idle: 0

server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:9000/eureka/"

